server.port: 8081
spring:
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://teamteach.clx92rbt29sc.ap-south-1.rds.amazonaws.com:3306/profile_mgmt
    username: admin
    password: DigiSherpa21
  jpa:
    hibernate.ddl-auto: update
    generate-ddl: true
    show-sql: true

app:
  security:
    jwt:
      authtype: Bearer
      expirationmins: 45
      uri: asd
      header: jjh
    authentication:
      type: DBBASED
    key:
      keytype: shared
      signingsecret: fe80::6184:62f1:2b9e:5b8313:8666:1qaz